=== OpenIdentityPlatform/OpenIG/openig-core/src/main/resources/org/forgerock/openig/handler/router/route.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "i18n:org/forgerock/openig/handler/router/route#schema.desc",

  "properties": {
    "handler": {
        "description": "i18n:org/forgerock/openig/handler/router/route#handler.desc",
        "type": "string"
    },
    "condition": {
      "description": "i18n:org/forgerock/openig/handler/router/route#condition.desc",
      "type": "string"
    },
    "heap": {
      "description": "i18n:org/forgerock/openig/handler/router/route#heap.desc",
      "type": "array",
      "items": {
        "description": "i18n:org/forgerock/openig/handler/router/route#heap-object.desc",
        "type": "object",
        "properties": {
          "name": {
            "description": "i18n:org/forgerock/openig/handler/router/route#heap-object-name.desc",
            "type": "string"
          },
          "type": {
            "description": "i18n:org/forgerock/openig/handler/router/route#heap-object-type.desc",
            "type": "string"
          },
          "config": {
            "description": "i18n:org/forgerock/openig/handler/router/route#heap-object-config.desc",
            "type": "object"
          }
        },
        "required": [ "name", "type" ]
      }
    },
    "name": {
      "description": "i18n:org/forgerock/openig/handler/router/route#name.desc",
      "type": "string"
    }
  },
  "required": [ "handler" ]
}

=== OpenIdentityPlatform/OpenIG/openig-war/src/test/resources/routes/petstore-mock.json
{
  "name": "petstore-mock",
  "condition": "${matches(request.uri.path, '^/v2/')}",
  "heap": [
    {
      "name": "PetstoreMock",
      "type": "OpenApiMockResponseHandler",
      "config": {
        "spec": "${read('$$SWAGGER_FILE$$')}",
        "defaultStatusCode": 200,
        "arraySize": 2
      }
    }
  ],
  "handler": "PetstoreMock"
}
